//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyDriveUpload {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyDriveUpload.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update the podcasts since the device seems to be offline..
        /// </summary>
        internal static string CannotUpdateDeviceOffline {
            get {
                return ResourceManager.GetString("CannotUpdateDeviceOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update the podcasts since no data connection could be established.
        ///Please check the device&apos;s connectivity..
        /// </summary>
        internal static string CannotUpdateNoDataConnection {
            get {
                return ResourceManager.GetString("CannotUpdateNoDataConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update the podcasts because there is no wifi connection.
        ///Try updating via the cellular network?.
        /// </summary>
        internal static string CannotUpdateNoWifiConnection {
            get {
                return ResourceManager.GetString("CannotUpdateNoWifiConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Update.
        /// </summary>
        internal static string CannotUpdateTitle {
            get {
                return ResourceManager.GetString("CannotUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size ({0} MB) is bigger than the maximum size (5 MB) allowed for uploading via a cellular network.
        ///
        ///If you connect the phone to a Wifi network and an external power supply this limit will increase to 100 MB..
        /// </summary>
        internal static string CannotUploadMsgCellular {
            get {
                return ResourceManager.GetString("CannotUploadMsgCellular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size ({0} MB) is bigger than the maximum size (100 MB) allowed for uploading..
        /// </summary>
        internal static string CannotUploadMsgWifi {
            get {
                return ResourceManager.GetString("CannotUploadMsgWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size ({0} MB) is bigger than the maximum size (5 MB) allowed for uploading via Wifi while running on battery.
        ///
        ///If you connect the phone to an external power supply this limit will be 100MB..
        /// </summary>
        internal static string CannotUploadMsgWifiBattery {
            get {
                return ResourceManager.GetString("CannotUploadMsgWifiBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot upload file.
        /// </summary>
        internal static string CannotUploadTitle {
            get {
                return ResourceManager.GetString("CannotUploadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload episode:
        ///{0}.
        /// </summary>
        internal static string FailedToUpload {
            get {
                return ResourceManager.GetString("FailedToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed.
        /// </summary>
        internal static string FailedToUploadTitle {
            get {
                return ResourceManager.GetString("FailedToUploadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sign in:
        ///{0}.
        /// </summary>
        internal static string SignInFailure {
            get {
                return ResourceManager.GetString("SignInFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in failed.
        /// </summary>
        internal static string SignInFailureTitle {
            get {
                return ResourceManager.GetString("SignInFailureTitle", resourceCulture);
            }
        }
    }
}
